services:
  fhem-dev:
    environment:
      FHEM_SVN_ROOT: ${FHEM_SVN_ROOT:-/workspace/fhem-svn/fhem}
    volumes:
      - ../../fhem-svn:/workspace/fhem-svn
      - ${HOME}/.ssh:/home/sven/.ssh:ro
      - ${HOME}/.subversion:/home/sven/.subversion
